In [1]:
import pandas as pd
import numpy as np

In [2]:
dict = {
    "name" : ["ram", "shubh", "raj", "rohan"],
    "marks" : [23, 43, 76, 29],
    "city" : ["los", "delhi", "goa", "ranchi"]
}

In [3]:
# DataFrame converts into kinda excel sheet makes easier to use numpy
df = pd.DataFrame(dict)

In [4]:
print(df)

    name  marks    city
0    ram     23     los
1  shubh     43   delhi
2    raj     76     goa
3  rohan     29  ranchi

In [5]:
df

    name  marks    city
0    ram     23     los
1  shubh     43   delhi
2    raj     76     goa
3  rohan     29  ranchi

In [6]:
# Converting df to a csv file that will be saved in homepage of notebook
df.to_csv('anyname.csv', index = False)                    # index is the starting number in each row

In [7]:
df.head(0)                                                 # from heading no. of rows

Empty DataFrame
Columns: [name, marks, city]
Index: []

In [8]:
df.tail(3)                                                 # from bottommost row

    name  marks    city
1  shubh     43   delhi
2    raj     76     goa
3  rohan     29  ranchi

In [9]:
# basic statistic details
df.describe()

          marks
count   4.00000
mean   42.75000
std    23.69775
min    23.00000
25%    27.50000
50%    36.00000
75%    51.25000
max    76.00000

In [10]:
# to read from any csv file
df = pd.read_csv("file_name.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'file_name.csv'

In [11]:
df['marks']

0    23
1    43
2    76
3    29
Name: marks, dtype: int64

In [12]:
df['name'][3] = 'prem'
df

C:\Users\maste\AppData\Local\Temp\ipykernel_20888\3102198989.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['name'][3] = 'prem'
C:\Users\maste\AppData\Local\Temp\ipykernel_20888\3102198989.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['name'][3] = 'prem'

    name  marks    city
0    ram     23     los
1  shubh     43   delhi
2    raj     76     goa
3   prem     29  ranchi

In [13]:
df.index = [1, 'two', 3, 4]
df

      name  marks    city
1      ram     23     los
two  shubh     43   delhi
3      raj     76     goa
4     prem     29  ranchi

In [14]:
# Series -> 1D array
ser = pd.Series(np.random.rand(7))
ser

0    0.110847
1    0.157816
2    0.622620
3    0.690606
4    0.753456
5    0.110580
6    0.145265
dtype: float64

In [15]:
# to convert to numpy array
ser.to_numpy()

array([0.110847  , 0.15781577, 0.62262016, 0.69060611, 0.75345624,
       0.11057997, 0.14526512])

In [16]:
ser.sort_index(axis = 0, ascending = False)
ser

0    0.110847
1    0.157816
2    0.622620
3    0.690606
4    0.753456
5    0.110580
6    0.145265
dtype: float64

In [20]:
newdf = pd.DataFrame(np.random.rand(30,5), index = np.arange(30))
newdf

           0         1         2         3         4
0   0.134560  0.030297  0.384882  0.104373  0.799005
1   0.000729  0.000580  0.939596  0.252193  0.842778
2   0.435125  0.831783  0.315586  0.209751  0.360134
3   0.222303  0.952855  0.103110  0.615513  0.105274
4   0.446832  0.527283  0.297970  0.582494  0.847480
5   0.590056  0.082908  0.406613  0.704111  0.082398
6   0.041157  0.178458  0.985191  0.632264  0.330003
7   0.554120  0.826039  0.319980  0.866483  0.577502
8   0.946401  0.665194  0.089302  0.083557  0.836195
9   0.719027  0.817814  0.844692  0.672236  0.049083
10  0.777539  0.834451  0.623312  0.720946  0.973125
11  0.871251  0.778492  0.886325  0.454567  0.897627
12  0.470696  0.547462  0.159657  0.653830  0.719326
13  0.546445  0.292618  0.181394  0.590749  0.819583
14  0.839788  0.280570  0.139106  0.858199  0.949312
15  0.364396  0.840408  0.626353  0.298239  0.901363
16  0.456550  0.064428  0.795475  0.097127  0.278509
17  0.479176  0.991887  0.637985  0.321175  0.672821
18  0.238615  0.982810  0.090710  0.697754  0.416232
19  0.111746  0.822301  0.535105  0.541362  0.187822
20  0.915677  0.270340  0.002478  0.489128  0.441131
21  0.241103  0.354482  0.115480  0.147108  0.679891
22  0.664692  0.209758  0.161279  0.315336  0.721981
23  0.530775  0.600542  0.508529  0.336825  0.855562
24  0.372810  0.406237  0.109446  0.603338  0.652529
25  0.300889  0.040740  0.023422  0.503943  0.480707
26  0.378679  0.146719  0.018844  0.616888  0.302521
27  0.641492  0.853181  0.087859  0.308658  0.396628
28  0.080468  0.417414  0.945246  0.368761  0.553190
29  0.086953  0.900346  0.035439  0.358329  0.875288

In [21]:
newdf2 = newdf               # It has became view means they point to same memory location
newdf2[0][0] = 32
newdf2

C:\Users\maste\AppData\Local\Temp\ipykernel_20888\1682853796.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  newdf2[0][0] = 32

            0         1         2         3         4
0   32.000000  0.030297  0.384882  0.104373  0.799005
1    0.000729  0.000580  0.939596  0.252193  0.842778
2    0.435125  0.831783  0.315586  0.209751  0.360134
3    0.222303  0.952855  0.103110  0.615513  0.105274
4    0.446832  0.527283  0.297970  0.582494  0.847480
5    0.590056  0.082908  0.406613  0.704111  0.082398
6    0.041157  0.178458  0.985191  0.632264  0.330003
7    0.554120  0.826039  0.319980  0.866483  0.577502
8    0.946401  0.665194  0.089302  0.083557  0.836195
9    0.719027  0.817814  0.844692  0.672236  0.049083
10   0.777539  0.834451  0.623312  0.720946  0.973125
11   0.871251  0.778492  0.886325  0.454567  0.897627
12   0.470696  0.547462  0.159657  0.653830  0.719326
13   0.546445  0.292618  0.181394  0.590749  0.819583
14   0.839788  0.280570  0.139106  0.858199  0.949312
15   0.364396  0.840408  0.626353  0.298239  0.901363
16   0.456550  0.064428  0.795475  0.097127  0.278509
17   0.479176  0.991887  0.637985  0.321175  0.672821
18   0.238615  0.982810  0.090710  0.697754  0.416232
19   0.111746  0.822301  0.535105  0.541362  0.187822
20   0.915677  0.270340  0.002478  0.489128  0.441131
21   0.241103  0.354482  0.115480  0.147108  0.679891
22   0.664692  0.209758  0.161279  0.315336  0.721981
23   0.530775  0.600542  0.508529  0.336825  0.855562
24   0.372810  0.406237  0.109446  0.603338  0.652529
25   0.300889  0.040740  0.023422  0.503943  0.480707
26   0.378679  0.146719  0.018844  0.616888  0.302521
27   0.641492  0.853181  0.087859  0.308658  0.396628
28   0.080468  0.417414  0.945246  0.368761  0.553190
29   0.086953  0.900346  0.035439  0.358329  0.875288

In [22]:
newdf

            0         1         2         3         4
0   32.000000  0.030297  0.384882  0.104373  0.799005
1    0.000729  0.000580  0.939596  0.252193  0.842778
2    0.435125  0.831783  0.315586  0.209751  0.360134
3    0.222303  0.952855  0.103110  0.615513  0.105274
4    0.446832  0.527283  0.297970  0.582494  0.847480
5    0.590056  0.082908  0.406613  0.704111  0.082398
6    0.041157  0.178458  0.985191  0.632264  0.330003
7    0.554120  0.826039  0.319980  0.866483  0.577502
8    0.946401  0.665194  0.089302  0.083557  0.836195
9    0.719027  0.817814  0.844692  0.672236  0.049083
10   0.777539  0.834451  0.623312  0.720946  0.973125
11   0.871251  0.778492  0.886325  0.454567  0.897627
12   0.470696  0.547462  0.159657  0.653830  0.719326
13   0.546445  0.292618  0.181394  0.590749  0.819583
14   0.839788  0.280570  0.139106  0.858199  0.949312
15   0.364396  0.840408  0.626353  0.298239  0.901363
16   0.456550  0.064428  0.795475  0.097127  0.278509
17   0.479176  0.991887  0.637985  0.321175  0.672821
18   0.238615  0.982810  0.090710  0.697754  0.416232
19   0.111746  0.822301  0.535105  0.541362  0.187822
20   0.915677  0.270340  0.002478  0.489128  0.441131
21   0.241103  0.354482  0.115480  0.147108  0.679891
22   0.664692  0.209758  0.161279  0.315336  0.721981
23   0.530775  0.600542  0.508529  0.336825  0.855562
24   0.372810  0.406237  0.109446  0.603338  0.652529
25   0.300889  0.040740  0.023422  0.503943  0.480707
26   0.378679  0.146719  0.018844  0.616888  0.302521
27   0.641492  0.853181  0.087859  0.308658  0.396628
28   0.080468  0.417414  0.945246  0.368761  0.553190
29   0.086953  0.900346  0.035439  0.358329  0.875288

In [30]:
newdf3 = newdf.copy()                 # newdf.copy() creates the copy of the newdf
newdf3[0][2] = 1
newdf3

C:\Users\maste\AppData\Local\Temp\ipykernel_20888\3082236796.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  newdf3[0][2] = 1

            0         1         2         3         4
0   32.000000  0.030297  0.384882  0.104373  0.799005
1    1.000000  0.000580  0.939596  0.252193  0.842778
2    1.000000  0.831783  0.315586  0.209751  0.360134
3    0.222303  0.952855  0.103110  0.615513  0.105274
4    0.446832  0.527283  0.297970  0.582494  0.847480
5    0.590056  0.082908  0.406613  0.704111  0.082398
6    0.041157  0.178458  0.985191  0.632264  0.330003
7    0.554120  0.826039  0.319980  0.866483  0.577502
8    0.946401  0.665194  0.089302  0.083557  0.836195
9    0.719027  0.817814  0.844692  0.672236  0.049083
10   0.777539  0.834451  0.623312  0.720946  0.973125
11   0.871251  0.778492  0.886325  0.454567  0.897627
12   0.470696  0.547462  0.159657  0.653830  0.719326
13   0.546445  0.292618  0.181394  0.590749  0.819583
14   0.839788  0.280570  0.139106  0.858199  0.949312
15   0.364396  0.840408  0.626353  0.298239  0.901363
16   0.456550  0.064428  0.795475  0.097127  0.278509
17   0.479176  0.991887  0.637985  0.321175  0.672821
18   0.238615  0.982810  0.090710  0.697754  0.416232
19   0.111746  0.822301  0.535105  0.541362  0.187822
20   0.915677  0.270340  0.002478  0.489128  0.441131
21   0.241103  0.354482  0.115480  0.147108  0.679891
22   0.664692  0.209758  0.161279  0.315336  0.721981
23   0.530775  0.600542  0.508529  0.336825  0.855562
24   0.372810  0.406237  0.109446  0.603338  0.652529
25   0.300889  0.040740  0.023422  0.503943  0.480707
26   0.378679  0.146719  0.018844  0.616888  0.302521
27   0.641492  0.853181  0.087859  0.308658  0.396628
28   0.080468  0.417414  0.945246  0.368761  0.553190
29   0.086953  0.900346  0.035439  0.358329  0.875288

#### The given error when we give a value to a particular index gives error as sometimes pandas allocate it as view and sometimes as copy so it is very inefficient to change dataframe or series like that so instead we use loc to modify or update the values

In [29]:
newdf

            0         1         2         3         4
0   32.000000  0.030297  0.384882  0.104373  0.799005
1    1.000000  0.000580  0.939596  0.252193  0.842778
2    0.435125  0.831783  0.315586  0.209751  0.360134
3    0.222303  0.952855  0.103110  0.615513  0.105274
4    0.446832  0.527283  0.297970  0.582494  0.847480
5    0.590056  0.082908  0.406613  0.704111  0.082398
6    0.041157  0.178458  0.985191  0.632264  0.330003
7    0.554120  0.826039  0.319980  0.866483  0.577502
8    0.946401  0.665194  0.089302  0.083557  0.836195
9    0.719027  0.817814  0.844692  0.672236  0.049083
10   0.777539  0.834451  0.623312  0.720946  0.973125
11   0.871251  0.778492  0.886325  0.454567  0.897627
12   0.470696  0.547462  0.159657  0.653830  0.719326
13   0.546445  0.292618  0.181394  0.590749  0.819583
14   0.839788  0.280570  0.139106  0.858199  0.949312
15   0.364396  0.840408  0.626353  0.298239  0.901363
16   0.456550  0.064428  0.795475  0.097127  0.278509
17   0.479176  0.991887  0.637985  0.321175  0.672821
18   0.238615  0.982810  0.090710  0.697754  0.416232
19   0.111746  0.822301  0.535105  0.541362  0.187822
20   0.915677  0.270340  0.002478  0.489128  0.441131
21   0.241103  0.354482  0.115480  0.147108  0.679891
22   0.664692  0.209758  0.161279  0.315336  0.721981
23   0.530775  0.600542  0.508529  0.336825  0.855562
24   0.372810  0.406237  0.109446  0.603338  0.652529
25   0.300889  0.040740  0.023422  0.503943  0.480707
26   0.378679  0.146719  0.018844  0.616888  0.302521
27   0.641492  0.853181  0.087859  0.308658  0.396628
28   0.080468  0.417414  0.945246  0.368761  0.553190
29   0.086953  0.900346  0.035439  0.358329  0.875288

In [31]:
newdf.columns = list("ABCDE")
newdf

            A         B         C         D         E
0   32.000000  0.030297  0.384882  0.104373  0.799005
1    1.000000  0.000580  0.939596  0.252193  0.842778
2    0.435125  0.831783  0.315586  0.209751  0.360134
3    0.222303  0.952855  0.103110  0.615513  0.105274
4    0.446832  0.527283  0.297970  0.582494  0.847480
5    0.590056  0.082908  0.406613  0.704111  0.082398
6    0.041157  0.178458  0.985191  0.632264  0.330003
7    0.554120  0.826039  0.319980  0.866483  0.577502
8    0.946401  0.665194  0.089302  0.083557  0.836195
9    0.719027  0.817814  0.844692  0.672236  0.049083
10   0.777539  0.834451  0.623312  0.720946  0.973125
11   0.871251  0.778492  0.886325  0.454567  0.897627
12   0.470696  0.547462  0.159657  0.653830  0.719326
13   0.546445  0.292618  0.181394  0.590749  0.819583
14   0.839788  0.280570  0.139106  0.858199  0.949312
15   0.364396  0.840408  0.626353  0.298239  0.901363
16   0.456550  0.064428  0.795475  0.097127  0.278509
17   0.479176  0.991887  0.637985  0.321175  0.672821
18   0.238615  0.982810  0.090710  0.697754  0.416232
19   0.111746  0.822301  0.535105  0.541362  0.187822
20   0.915677  0.270340  0.002478  0.489128  0.441131
21   0.241103  0.354482  0.115480  0.147108  0.679891
22   0.664692  0.209758  0.161279  0.315336  0.721981
23   0.530775  0.600542  0.508529  0.336825  0.855562
24   0.372810  0.406237  0.109446  0.603338  0.652529
25   0.300889  0.040740  0.023422  0.503943  0.480707
26   0.378679  0.146719  0.018844  0.616888  0.302521
27   0.641492  0.853181  0.087859  0.308658  0.396628
28   0.080468  0.417414  0.945246  0.368761  0.553190
29   0.086953  0.900346  0.035439  0.358329  0.875288

In [32]:
newdf.loc[0, 0] = 45
newdf

            A         B         C         D         E     0
0   32.000000  0.030297  0.384882  0.104373  0.799005  45.0
1    1.000000  0.000580  0.939596  0.252193  0.842778   NaN
2    0.435125  0.831783  0.315586  0.209751  0.360134   NaN
3    0.222303  0.952855  0.103110  0.615513  0.105274   NaN
4    0.446832  0.527283  0.297970  0.582494  0.847480   NaN
5    0.590056  0.082908  0.406613  0.704111  0.082398   NaN
6    0.041157  0.178458  0.985191  0.632264  0.330003   NaN
7    0.554120  0.826039  0.319980  0.866483  0.577502   NaN
8    0.946401  0.665194  0.089302  0.083557  0.836195   NaN
9    0.719027  0.817814  0.844692  0.672236  0.049083   NaN
10   0.777539  0.834451  0.623312  0.720946  0.973125   NaN
11   0.871251  0.778492  0.886325  0.454567  0.897627   NaN
12   0.470696  0.547462  0.159657  0.653830  0.719326   NaN
13   0.546445  0.292618  0.181394  0.590749  0.819583   NaN
14   0.839788  0.280570  0.139106  0.858199  0.949312   NaN
15   0.364396  0.840408  0.626353  0.298239  0.901363   NaN
16   0.456550  0.064428  0.795475  0.097127  0.278509   NaN
17   0.479176  0.991887  0.637985  0.321175  0.672821   NaN
18   0.238615  0.982810  0.090710  0.697754  0.416232   NaN
19   0.111746  0.822301  0.535105  0.541362  0.187822   NaN
20   0.915677  0.270340  0.002478  0.489128  0.441131   NaN
21   0.241103  0.354482  0.115480  0.147108  0.679891   NaN
22   0.664692  0.209758  0.161279  0.315336  0.721981   NaN
23   0.530775  0.600542  0.508529  0.336825  0.855562   NaN
24   0.372810  0.406237  0.109446  0.603338  0.652529   NaN
25   0.300889  0.040740  0.023422  0.503943  0.480707   NaN
26   0.378679  0.146719  0.018844  0.616888  0.302521   NaN
27   0.641492  0.853181  0.087859  0.308658  0.396628   NaN
28   0.080468  0.417414  0.945246  0.368761  0.553190   NaN
29   0.086953  0.900346  0.035439  0.358329  0.875288   NaN

In [34]:
newdf.drop(0, axis = 1)

            A         B         C         D         E
0   32.000000  0.030297  0.384882  0.104373  0.799005
1    1.000000  0.000580  0.939596  0.252193  0.842778
2    0.435125  0.831783  0.315586  0.209751  0.360134
3    0.222303  0.952855  0.103110  0.615513  0.105274
4    0.446832  0.527283  0.297970  0.582494  0.847480
5    0.590056  0.082908  0.406613  0.704111  0.082398
6    0.041157  0.178458  0.985191  0.632264  0.330003
7    0.554120  0.826039  0.319980  0.866483  0.577502
8    0.946401  0.665194  0.089302  0.083557  0.836195
9    0.719027  0.817814  0.844692  0.672236  0.049083
10   0.777539  0.834451  0.623312  0.720946  0.973125
11   0.871251  0.778492  0.886325  0.454567  0.897627
12   0.470696  0.547462  0.159657  0.653830  0.719326
13   0.546445  0.292618  0.181394  0.590749  0.819583
14   0.839788  0.280570  0.139106  0.858199  0.949312
15   0.364396  0.840408  0.626353  0.298239  0.901363
16   0.456550  0.064428  0.795475  0.097127  0.278509
17   0.479176  0.991887  0.637985  0.321175  0.672821
18   0.238615  0.982810  0.090710  0.697754  0.416232
19   0.111746  0.822301  0.535105  0.541362  0.187822
20   0.915677  0.270340  0.002478  0.489128  0.441131
21   0.241103  0.354482  0.115480  0.147108  0.679891
22   0.664692  0.209758  0.161279  0.315336  0.721981
23   0.530775  0.600542  0.508529  0.336825  0.855562
24   0.372810  0.406237  0.109446  0.603338  0.652529
25   0.300889  0.040740  0.023422  0.503943  0.480707
26   0.378679  0.146719  0.018844  0.616888  0.302521
27   0.641492  0.853181  0.087859  0.308658  0.396628
28   0.080468  0.417414  0.945246  0.368761  0.553190
29   0.086953  0.900346  0.035439  0.358329  0.875288

In [36]:
newdf                                    # It doesn't change until you update the df

            A         B         C         D         E     0
0   32.000000  0.030297  0.384882  0.104373  0.799005  45.0
1    1.000000  0.000580  0.939596  0.252193  0.842778   NaN
2    0.435125  0.831783  0.315586  0.209751  0.360134   NaN
3    0.222303  0.952855  0.103110  0.615513  0.105274   NaN
4    0.446832  0.527283  0.297970  0.582494  0.847480   NaN
5    0.590056  0.082908  0.406613  0.704111  0.082398   NaN
6    0.041157  0.178458  0.985191  0.632264  0.330003   NaN
7    0.554120  0.826039  0.319980  0.866483  0.577502   NaN
8    0.946401  0.665194  0.089302  0.083557  0.836195   NaN
9    0.719027  0.817814  0.844692  0.672236  0.049083   NaN
10   0.777539  0.834451  0.623312  0.720946  0.973125   NaN
11   0.871251  0.778492  0.886325  0.454567  0.897627   NaN
12   0.470696  0.547462  0.159657  0.653830  0.719326   NaN
13   0.546445  0.292618  0.181394  0.590749  0.819583   NaN
14   0.839788  0.280570  0.139106  0.858199  0.949312   NaN
15   0.364396  0.840408  0.626353  0.298239  0.901363   NaN
16   0.456550  0.064428  0.795475  0.097127  0.278509   NaN
17   0.479176  0.991887  0.637985  0.321175  0.672821   NaN
18   0.238615  0.982810  0.090710  0.697754  0.416232   NaN
19   0.111746  0.822301  0.535105  0.541362  0.187822   NaN
20   0.915677  0.270340  0.002478  0.489128  0.441131   NaN
21   0.241103  0.354482  0.115480  0.147108  0.679891   NaN
22   0.664692  0.209758  0.161279  0.315336  0.721981   NaN
23   0.530775  0.600542  0.508529  0.336825  0.855562   NaN
24   0.372810  0.406237  0.109446  0.603338  0.652529   NaN
25   0.300889  0.040740  0.023422  0.503943  0.480707   NaN
26   0.378679  0.146719  0.018844  0.616888  0.302521   NaN
27   0.641492  0.853181  0.087859  0.308658  0.396628   NaN
28   0.080468  0.417414  0.945246  0.368761  0.553190   NaN
29   0.086953  0.900346  0.035439  0.358329  0.875288   NaN

In [39]:
newdf = newdf.drop(0)
newdf

           A         B         C         D         E
1   1.000000  0.000580  0.939596  0.252193  0.842778
2   0.435125  0.831783  0.315586  0.209751  0.360134
3   0.222303  0.952855  0.103110  0.615513  0.105274
4   0.446832  0.527283  0.297970  0.582494  0.847480
5   0.590056  0.082908  0.406613  0.704111  0.082398
6   0.041157  0.178458  0.985191  0.632264  0.330003
7   0.554120  0.826039  0.319980  0.866483  0.577502
8   0.946401  0.665194  0.089302  0.083557  0.836195
9   0.719027  0.817814  0.844692  0.672236  0.049083
10  0.777539  0.834451  0.623312  0.720946  0.973125
11  0.871251  0.778492  0.886325  0.454567  0.897627
12  0.470696  0.547462  0.159657  0.653830  0.719326
13  0.546445  0.292618  0.181394  0.590749  0.819583
14  0.839788  0.280570  0.139106  0.858199  0.949312
15  0.364396  0.840408  0.626353  0.298239  0.901363
16  0.456550  0.064428  0.795475  0.097127  0.278509
17  0.479176  0.991887  0.637985  0.321175  0.672821
18  0.238615  0.982810  0.090710  0.697754  0.416232
19  0.111746  0.822301  0.535105  0.541362  0.187822
20  0.915677  0.270340  0.002478  0.489128  0.441131
21  0.241103  0.354482  0.115480  0.147108  0.679891
22  0.664692  0.209758  0.161279  0.315336  0.721981
23  0.530775  0.600542  0.508529  0.336825  0.855562
24  0.372810  0.406237  0.109446  0.603338  0.652529
25  0.300889  0.040740  0.023422  0.503943  0.480707
26  0.378679  0.146719  0.018844  0.616888  0.302521
27  0.641492  0.853181  0.087859  0.308658  0.396628
28  0.080468  0.417414  0.945246  0.368761  0.553190
29  0.086953  0.900346  0.035439  0.358329  0.875288

In [41]:
# To observe certain sections only
newdf.loc[[2, 3], ["D", "E"]]

          D         E
2  0.209751  0.360134
3  0.615513  0.105274

In [44]:
newdf.loc[(newdf["E"] < 0.3)]

           A         B         C         D         E
3   0.222303  0.952855  0.103110  0.615513  0.105274
5   0.590056  0.082908  0.406613  0.704111  0.082398
9   0.719027  0.817814  0.844692  0.672236  0.049083
16  0.456550  0.064428  0.795475  0.097127  0.278509
19  0.111746  0.822301  0.535105  0.541362  0.187822

In [45]:
# To do indexing from index only then use iloc
newdf.iloc[0, 3]

np.float64(0.25219287004752355)

In [49]:
newdf.drop([5], inplace = True)               # This replaces original dataframe

In [50]:
newdf['B'].isnull()                           # Checks if it is None or not

1     False
2     False
3     False
4     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
Name: B, dtype: bool